# Generated by Django 5.0.7 on 2025-02-07 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Poat",
            new_name="Post",
        ),
    ]
