# Generated by Django 5.1.5 on 2025-02-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feature",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
